# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DI-Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DI-Sample
  pod 'Swinject'

  target 'DI-SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DI-SampleUITests' do
    # Pods for testing
  end

end
